/**
 * Message Type Detection Utility
 *
 * Determines whether an assistant message was generated by council execution
 * or workflow execution, and provides normalized data access.
 */

/**
 * Execution mode constants
 */
export const EXECUTION_MODE = {
  COUNCIL: 'council',
  WORKFLOW: 'workflow',
  UNKNOWN: 'unknown'
};

/**
 * Detect the execution mode of an assistant message
 *
 * @param {Object} message - Assistant message object
 * @returns {string} - Execution mode: 'council', 'workflow', or 'unknown'
 */
export function detectExecutionMode(message) {
  if (!message || message.role !== 'assistant') {
    return EXECUTION_MODE.UNKNOWN;
  }

  // Workflow execution: has 'variables' field
  if (message.variables !== undefined) {
    return EXECUTION_MODE.WORKFLOW;
  }

  // Council execution: has 'stage3' field (final synthesis)
  if (message.stage3 !== undefined) {
    return EXECUTION_MODE.COUNCIL;
  }

  // Partial council message: has stage1 or stage2 but not stage3 yet
  if (message.stage1 !== undefined || message.stage2 !== undefined) {
    return EXECUTION_MODE.COUNCIL;
  }

  return EXECUTION_MODE.UNKNOWN;
}

/**
 * Get the final output content from an assistant message
 *
 * @param {Object} message - Assistant message object
 * @returns {string|null} - Final output content or null
 */
export function getFinalOutput(message) {
  const mode = detectExecutionMode(message);

  if (mode === EXECUTION_MODE.COUNCIL) {
    return message.stage3?.response || null;
  }

  if (mode === EXECUTION_MODE.WORKFLOW) {
    // Convention: last variable is the final output
    const variables = message.variables;
    if (!variables || Object.keys(variables).length === 0) {
      return null;
    }

    const varNames = Object.keys(variables);
    const lastVar = varNames[varNames.length - 1];
    const content = variables[lastVar];

    // Convert to string if needed
    if (typeof content === 'string') {
      return content;
    }
    return JSON.stringify(content, null, 2);
  }

  return null;
}

/**
 * Check if a message is complete (all stages/steps finished)
 *
 * @param {Object} message - Assistant message object
 * @returns {boolean} - True if message is complete
 */
export function isMessageComplete(message) {
  const mode = detectExecutionMode(message);

  if (mode === EXECUTION_MODE.COUNCIL) {
    // Council is complete when stage3 exists
    return message.stage3 !== undefined;
  }

  if (mode === EXECUTION_MODE.WORKFLOW) {
    // Workflow is complete when variables exist and no partial flag
    return message.variables !== undefined && !message.partial;
  }

  return false;
}

/**
 * Get workflow metadata from a workflow message
 *
 * @param {Object} message - Assistant message object
 * @returns {Object|null} - Workflow metadata or null
 */
export function getWorkflowMetadata(message) {
  if (detectExecutionMode(message) !== EXECUTION_MODE.WORKFLOW) {
    return null;
  }

  return message.metadata || null;
}

/**
 * Get normalized display data for rendering
 *
 * @param {Object} message - Assistant message object
 * @returns {Object} - Normalized data structure
 */
export function getDisplayData(message) {
  const mode = detectExecutionMode(message);

  if (mode === EXECUTION_MODE.COUNCIL) {
    return {
      mode: EXECUTION_MODE.COUNCIL,
      stage1: message.stage1 || null,
      stage1_5: message.stage1_5 || null,
      stage2: message.stage2 || null,
      stage3: message.stage3 || null,
      metadata: message.metadata || null,
      isComplete: isMessageComplete(message)
    };
  }

  if (mode === EXECUTION_MODE.WORKFLOW) {
    return {
      mode: EXECUTION_MODE.WORKFLOW,
      variables: message.variables || {},
      workerOutputs: message.worker_outputs || {},
      metadata: message.metadata || null,
      isComplete: isMessageComplete(message),
      finalOutput: getFinalOutput(message)
    };
  }

  return {
    mode: EXECUTION_MODE.UNKNOWN,
    isComplete: false
  };
}
